### ISSUE TITLE
Incorrect source list is inserted on systems using deb822 style sources.list(Ubuntu >= 22.04)

### ISSUE THREAD

**Issue by brlin-tw** [chusiang/switch-apt-mirror.ansible.role#3]
Since the ~~22.04~~ 24.04 release of Ubuntu(and recent releases of the Debian distribution) switches to the deb822 style sources list format.

Ubuntu no longer uses the /etc/apt/sources.list file for its software sources, but rather uses the /etc/apt/sources.list.d/ubuntu.sources file for the configuration.  Currently this role will insert redundant software sources information at /etc/apt/sources.list and should be fixed.

## References

* The sources.list(5) manual page.
* [deb822 sources management - Ubuntu 24.04 LTS (Noble Numbat) Release Notes - Release - Ubuntu Community Hub](https://discourse.ubuntu.com/t/ubuntu-24-04-lts-noble-numbat-release-notes/39890#deb822-sources-management-26)

**Comment by brlin-tw** [comment]
Here's a workaround to disable the logic on newer Ubuntu releases:

```yaml
- name: >-
    Use Taiwan local Ubuntu mirror to reduce package download time.
  # NOTE: Ubuntu >=24.04 uses the DEP822 software source format, which
  # isn't compatible with the chusiang.switch-apt-mirror role at the
  # moment
  when: >-
    ansible_distribution_file_variety == "Debian"
      and (
        ansible_distribution == "Ubuntu"
          and ansible_distribution_version < "24.04"
      )
  ansible.builtin.include_role:
    name: chusiang.switch-apt-mirror
    apply:
      become: true
```
